name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions

      - name: Install Node.js and npm
        uses: actions
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build 
        run: npm run build

      - name: 
        uses: actions
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions

      - name: Deploy
        uses: actions
        with:
          name: build
          path: build

      - name: Deploy to Firebase
        uses: w9jds
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
